### ISSUE TITLE
M5Stack Cardputer

### ISSUE THREAD

**Issue by UthdenTroll** [RetiredWizard/PyDOS#13]
Would it be possible for PyDOS to be supported on the M5Stack Cardputer? It has an ESP32-S3. Also someone has made a Micropython app launcher (MicroHydra), so that could potentially be used to launch PyDOS, as well as other apps. 

More of a question rather than an issue :)

**Comment by RetiredWizard** [comment]
I've updated PyDOS for the Cardputer so a fresh PyDOS install from the latest files from github should get you going. 

If you already have PyDOS installed on the Cardputer all you need to do is copy the files from the cpython/cardputer/lib folder in this repo to the /lib/ folder on your Cardputer and after a reset, the keyboard should work in PyDOS.

**Comment by UthdenTroll** [comment]
It works! Thanks for your work - playing around with it now!
