### ISSUE TITLE
'module' is not iterable error - hardware pins not usable

### ISSUE THREAD

**Issue by veryalien** [RetiredWizard/PyDOS#14]
There's a little bug in pydos_bcfg.py which gives an error 'module' is not iterable. Unfortunately that means none of the hardware pins are accessible from Pydos.

Line 77:
if 'I2S_DATA' in board:

Should be:
if 'I2S_DATA' in dir(board):

**Comment by RetiredWizard** [comment]
Thanks! Should be fixed now.
