### ISSUE TITLE
PyDOS beginning to take off!

### ISSUE THREAD

**Issue by richpl** [RetiredWizard/PyDOS#3]
https://www.youtube.com/watch?v=daQ7HGdBWec

**Comment by RetiredWizard** [comment]
@richpl Stumbled across another one :D https://www.youtube.com/watch?v=TuuMez6DYIw

**Comment by richpl** [comment]
@RetiredWizard, this is my favourite:

https://m.youtube.com/watch?v=91grzcqmgmY

I also see that PyDOS made the Adafruit blog today!

**Comment by RetiredWizard** [comment]
> @RetiredWizard, this is my favourite:
> 
> https://m.youtube.com/watch?v=91grzcqmgmY
> 
Yes, He does some fun stuff and did a nice demo of PyBasic. I've been watching his KIM-1 videos on getting adventure running on his emulator. It blows my mind that someone managed to code adventure on a KIM-1 :)
